project:
  type: website
  resources:
    - "images/twitter-card.png"
    - "materials/*.pdf"
    - "data/*"
  render:
    - "*.qmd"
    - "!README.Rmd"

website:
  page-navigation: true
  title: "Tidy time series & forecasting in R"
  description: "Homepage for time series analysis and forecasting workshop at R/Medicine 2024"
  site-url: "https://workshop.nectric.com.au/rmedicine2024"

  repo-url: https://github.com/mitchelloharawild/workshop-r-medicine-2024
  repo-actions: [edit, issue]

  # opengraph: true
  twitter-card:
    creator: "@mitchoharawild"
    image: "/images/twitter-card.png"

  favicon: "/images/fable.svg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2024, Mitchell O'Hara-Wild"
    background: "#426D98"

  navbar:
    background: "#426D98"
    pinned: true
    align: center
    right:
      - icon: download
        text: Downloads
        menu:
          - text: Everything
            href: 'https://github.com/mitchelloharawild/workshop-r-medicine-2024/archive/refs/heads/main.zip'
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/mitchelloharawild/workshop-r-medicine-2024
    left:
    - text: Slides
      menu:
        - text: Time series data and patterns
          href: materials/analysis/slides.qmd
        - text: Modelling and forecasting
          href: materials/modelling/slides.qmd
        - text: Accuracy evaluation
          href: materials/accuracy/slides.qmd
    - text: Feedback
      href: https://feedback.nectric.com.au/oZyK

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"
    include-after-body: plausible.html
